server:
  port: 8081
spring:
  cloud:     
     config:
       server:
          git:
            default-label: eureka
            uri: https://github.com/EdisonGarofalo1/Microservicios-Spring-boot-y-Spring-Cloud
            search-paths: config-data  
  application:
    name: config-service    